project:
  type: website
  output-dir: docs

website:
  title: "Lobos Labs"
  description: "Personal site and portfolio of Ethan Lobo"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - text: Assignments
        menu: 
          - assignments/assignment1.qmd
      - href: projects/projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
      - icon: github
        href: https://github.com/lobo017
        text: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/ethanlobo/
        text: LinkedIn
  page-navigation: true

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true