project:
  type: website
  output-dir: docs

website:
  title: "Lobos Labs"
  description: "Personal site and portfolio of Ethan Lobo"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - href: projects/projects.qmd
        text: Projects
      - href: resume.qmd
        text: Resume
      - icon: github
        href: https://github.com/lobo017
        text: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/ethanlobo/
        text: LinkedIn
  page-navigation: true

metadata:
  keywords: ["resume", "portfolio", "ethan lobo", "cognitive science", "coding", "web development", "AI", "machine learning", "Big Data", "data science", "data visualization", "data analysis", "computer science", "data engineering", "data structures"]
  description: "Portfolio site and resume of Ethan Lobo."
  author: "Ethan Lobo"

format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true